version: '3.8'

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data_volume:/data  # Mounts the named volume to /data
    env_file: ".env"
volumes:
  data_volume: